version : "3.7"

services:
    webapp_nuxt:
        image: edcilo/nuxtjs:1.0.0
        restart: always
        ports:
            - ${APP_PORT:-3000}:3000
        volumes:
            - ./app:/code/app
        environment:
            NUXT_ENV: ${APP_ENV:-development}
            APP_NAME: ${APP_NAME:-app}
            GMAPS_KEY: ${GMAPS_KEY}
            GANALYTICS_KEY: ${GANALYTICS_KEY}

    webapp_nginx:
        container_name: webapp_nginx
        image: nginx:alpine
        restart: always
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
        environment:
            - VIRTUAL_HOST=${SERVICE_WEBAPP_DNS}
            - LETSENCRYPT_HOST=${SERVICE_WEBAPP_DNS}
            - LETSENCRYPT_EMAIL=${SSL_LETSENCRYPT_EMAIL}

networks:
    default:
        external:
            name: edcNet
